dist: bionic
language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo apt update
  - sudo apt install swig dialog
  # envelope: needed to install swig for M2Crypto on bionic
script:
  #- ./convey.py --output --reprocess --headless --file tests/filter.csv --exclude-filter 1,foo --daemon false
  - python3 tests.py
  #- echo "foo" | ./convey.py --output --reprocess --headless --include-filter 1,foo --daemon false
