[uwsgi]
http = :26683
#https = :26683,certificate.pem,certificate.pem

# processes
processes = 4
threads = 8
enable-threads = true

# performance
master = true          
vacuum = true          
die-on-term = true

# timeouts
harakiri = 30      
socket-timeout = 30
http-timeout = 30
